name: bussiness_alert_sender_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  flutter_spinkit: ^5.2.0
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  modal_bottom_sheet: ^2.1.2
  persistent_bottom_nav_bar_v2: ^4.2.8
  top_snackbar_flutter: ^3.1.0
  flutter_launcher_icons: ^0.13.1
  http: ^1.1.0
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  cloud_firestore: ^4.11.0
  firebase_messaging: ^14.7.1
  flutter_local_notifications: ^16.1.0

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SourceHanSansJP-Bold
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Bold.otf
    - family: SourceHanSansJP-Regular
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Regular.otf

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/icon.png'
  adaptive_icon_background: '#9E9E9E'
  adaptive_icon_foreground: 'assets/images/icon_adaptive_foreground.png'